apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress
spec:
  podSelector: 
   matchLabels:
      app: public
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80
