apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  clusterIP: None
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app
  type: ClusterIP

