apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  template:
    spec:
      containers:
      - name: factorial
        image: damrongsak/factorial:job
      restartPolicy: Never
  backoffLimit: 4

