apiVersion: v1
kind: Pod
metadata:
  name: pod10
spec:
  containers:
  - image: busybox
    name: test-container
    command:
        -  "/bin/sh"
        -  "-c"
        -  "while true; do date; sleep 7; done >> /shared/app.log"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /shared
      name: shared-volume
  - image: busybox
    name: display-container
    command:
        -  "/bin/sh"
        -  "-c"
        -  "while true; do echo 'Display Log';cat /data/app.log; sleep 20; done"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /data
      name: shared-volume
  volumes:
   - name: shared-volume
     nfs:
       server: nfs.d8k.io
       path: /data/student0/storage0

