apiVersion: v1
kind: Pod
metadata:
  name: pod17
spec:
  containers:
  - name: cpu-demo
    image: polinux/stress
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "0.8"
      requests:
        cpu: "0.5"
    command: ["stress"]
    args: ["--cpu", "1"]

