apiVersion: v1
kind: Pod
metadata:
  name: pod11
spec:
  volumes:
    - name: vol-pv
      persistentVolumeClaim:
        claimName: pvc12
  containers:
    - name: pv-web
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: vol-pv

