apiVersion: v1
kind: Pod
metadata:
  name: pod20
spec:
  containers:
  - name: memory-demo
    image: polinux/stress
    resources:
      limits:
        memory: "8Gi"
      requests:
        memory: "8Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]

