apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-less
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Mi
  storageClassName: mystorage

