apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user1
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQm1UQ0NBUUlDQVFBd1dURUxNQWtHQTFVRUJoTUNWRWd4RERBS0JnTlZCQWdNQTBKTFN6RU1NQW9HQTFVRQpCd3dEUWt0TE1SRXdEd1lEVlFRS0RBaFRaV04xY21sMGVURUxNQWtHQTFVRUN3d0NTVlF4RGpBTUJnTlZCQU1NCkJYVnpaWEl4TUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDZWNVYmovQS9BNkVtYWYrK20KQTQ3cnI0MzA4dFNFMStxSHlIbFordTkrNjVLUEdWTXFOWGZrNzdjdzRwSHpheDZRM2g1dmFOV204alhOa2hvRwo2dEFjaWFoTmVZbGMya3Nuei9HdUNYT2grTE50djV4VUdhWXNGa1c0KzMwRi9oYWhMbmtxWDBSZ0tsZkRHYjJtClhhSzJrbk5xbXg1YkkyNnZ6cTROcVNidUx3SURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ1lFQUNWOUMKcWxuaFh1NXd3WllIa2kxRTkzT2xGOVdTOXNkR2ZSUHJib2U1Q0c0djBYY29Oam9lZVUyNEV6VVh4TW83M3Vxdgo3SFlJUXA0cFU4bzFwL1pLU3M2enpPalRCWFlyT0xEQ2VISnFnOXdZV2JHRjdEbmN1VHdyc0Z6TUZSZ1RldjVwCk5talRBcGovZGNjVkZXRm5PaHNCVE1aUTBpd3dLa3FTaHNlU3BqZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
